### ISSUE TITLE
Unable to build on macOS / OSX

### ISSUE THREAD

**Issue by jack-pappas** [Microsoft/visualfsharp#2114]
I'm unable to build the compiler from this repository on macOS (OS X), although I am able to build it from fsharp/fsharp. It seems like we should be able to build this repo on OS X (it's even mentioned in the README).

I'm opening this issue to track commits / PRs related to fixing the macOS build.

The issues I've discovered so far with macOS builds:

- [ ] Enable Jenkins builds for OSX (#2134)
  - [ ] Modify ``README`` to include Jenkins build status indicators
- [X] Travis CI builds need to be enabled (in ``.travis.yml``) for macOS / OS X (#2109)
- [X] ``build.sh`` and ``before_install.sh`` need some modifications to generalize Linux/Ubuntu-specific steps, or only run them when running on Linux/Ubuntu. (#2125)
- [ ] Some external build tasks called from ``.targets`` files need to be fixed to launch via ``mono`` or ``dotnet``.
  - [ ] ``*.fsx`` scripts called through ``fsi``
  - [ ] ``FsLexYacc.targets`` (which calls ``fslex.exe`` and ``fsyacc.exe``)

**Comment by jack-pappas** [comment]
@KevinRansom @dsyme @cartermp Can someone with admin rights for this repo enable travis CI builds? This repo isn't currently set up for them so we can't run CI builds for OS X; please see the link in the first checklist item (above).

**Comment by dsyme** [comment]
@jack-pappas I don't have the full admin rights ("You require admin rights to enable these repositories").   I'm not sure if the DevDiv folk will want to enable Travis - normally they use Jenkins.  It might be we/they have to repeat what you've done in the context of the Jenkins CI configurations.

**Comment by jack-pappas** [comment]
I'm fine with whatever CI setup the DevDiv folks want to use, so long as we can get an OSX job configured. The first commit I made here is for Travis CI but the rest of the changes are for OS X builds in general (i.e., aren't specific to any particular CI setup).

**Comment by dsyme** [comment]
@jack-pappas The OS for Jenkins list is here: https://github.com/Microsoft/visualfsharp/blob/master/netci.groovy#L7.  It might just be a matter of adding OSX there.

**Comment by jack-pappas** [comment]
@dsyme Yes, it looks like that should work. I've submitted PR #2134 with that change.

**Comment by jack-pappas** [comment]
Looks like the changes Don merged in #2442 fixed the macOS builds. I'm able to build ``master`` on my Mac now, so I'm going to close this issue.

There are some follow-up tasks I'll handle separately:
* @KevinRansom reverted the change I submitted in #2134 because the macOS builds were failing due to missing dependencies and build scripting issues. All of that should be fixed now (see the discussion on that issue for details), so I've asked Kevin to revert his commit to reinstate the ``OSX`` builds.
* The Linux/macOS builds currently build only the bare-minimum components (``net40``). I think we eventually want those builds to include everything we're building on Windows (minus the VS integration); it'd be really helpful to be able to run some/all of the test suite on Linux/Mac so CI builds can help catch regressions specifically affecting those platforms. I'll work on this here and there as time allows, gradually porting functionality from ``build.cmd`` to ``build.sh``.

**Comment by smoothdeveloper** [comment]
@jack-pappas please consider a .fsx script if you are going to work on making tests + other stuff runnable  on macOs.

I gave it a try to get initial build: https://github.com/smoothdeveloper/buildvisualfsharp

this could really help for windows users too down the road.

**Comment by jack-pappas** [comment]
@smoothdeveloper That's not a bad idea, but it does leave the question of how you'd bootstrap the compiler; you can only run an ``.fsx`` if you have ``fsi`` / ``fsharpi`` available. We could probably migrate a good chunk of the build scripts to FAKE-based ``*.fsx`` files but we'd still need a bit of cmd / sh scripting to deal with the bootstrapping part.

**Comment by smoothdeveloper** [comment]
@jack-pappas I haven't thought about the details and you probably know much more than me (especially bootstrap is sensible topic in a compiler repository :slightly_smiling_face:), my feeling is small steps in direction of using .fsx where possible will help people to get a better picture of build in this repository.

Not everyone is a shell/cmd expert, for me this is super obscure compared to plain F#, even if F# is a bit more verbose and require some tooling/helpers to be kept terse at the top level.

The current build scripts do lack structure and are mostly flat AFAIU, this can be improved incrementally if the mac/linux build of this repository use .fsx (that won't impact MSFT).
