### ISSUE TITLE
Locking down Visual Studio 2019 GA

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#6190]
Hey folks,

We're going to be locking down **this week** on VS 2019 GA in the compiler, language, tools, and FSharp.Core.

Here is what we plan on having done:

- [x] Merging master **as of Feburary 4th** (today) to dev16.0 and shipping everything merged into that branch
- [x] Fixing #5983 as this is a known compiler regression starting with F# 4.6
- [x] Merging all of the above into the .NET CLI 2.1.x and .NET CLI 2.2.x

This roughly translates into the following shipping with VS 2019 GA and the corresponding GA bits for .NET Core:

* F# 4.6 and FSharp.Core 4.6.x
* A working FSI on .NET Core via use of `dotnet fsi`, but without package management via `#r`
* All performance issues currently checked as completed in #6096
* All bug fixes and improvements in master and dev16.0 today

Our internal schedule mandates that we lock down now and ensure it is completed by the end of the week. We will then be focused on finding any show-stopper bugs so that we can have a clean initial release.

There are some additional candidates that may be worth getting in alongside what has already been mentioned:

- [x] #6011, as it is a fix to a tooling regression of an edge case we knowingly caused in service towards fixing a huge tooling performance problem
- [x] #6063, as this is a fully-functioning fix for a known performance issue; it just needs approval and merging
- [x] #5865, as this is a very small bug fix and slight behavior change to make IntelliSense a bit less "chatty" by default in VS

Anyone have additional candidates they think are essential to have delivered by VS 2019 GA and their corresponding .NET Core releases? Due to the time it takes to validate everything, we'd like to get things committed or explicitly scoped out now.

cc @auduchinok @nosami @dsyme @forki @alfonsogarciacaro

**Comment by gerardtoconnor** [comment]
is there any time to get any additional items in #6096 in and if so what would be the deadline to get PR in for?

**Comment by cartermp** [comment]
After chatting with @dsyme about #6189 we decided that this is easiest just to do out of band, and should definitely be doable well before we fully release F# 4.6.

**Comment by cartermp** [comment]
All candidate PRs are merged and will undergo validation. What remains is insertions into .NET Core.

**Comment by cartermp** [comment]
.NET Core and VS 2019 bits have been shuffled into their respective places. Closing this out!
