### ISSUE TITLE
Collection of issues with byref analysis

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#862]
There are a number of holes in checking the use of byref values.  I'm collecting these into one issue since if we fix any one of them we may as well go through and address them all.  

Addressed:
* [x] Compiler allows invalid uses of byref in interface methods https://github.com/Microsoft/visualfsharp/issues/127 (Related to #5459)
* [x] Tupling causes problems in argument poitions https://github.com/Microsoft/visualfsharp/issues/3362 (Doesn't fail in Release, but dies in Debug)
* [x] Base calls and byrefs: https://github.com/Microsoft/visualfsharp/issues/130
* [x] Inlined tupled arguments and byrefs: https://github.com/Microsoft/visualfsharp/issues/820 and https://github.com/Microsoft/visualfsharp/issues/558
* [x] Struct field returns https://github.com/Microsoft/visualfsharp/issues/1401
* [x] Some uses of currying and byrefs: https://github.com/Microsoft/visualfsharp/issues/819

I'll close the individual bug entries and reactivate if we don't fix them all in one go.

**Comment by kbattocchi** [comment]
Would it make sense to tackle (parts of) [this planned User Voice item](https://fslang.uservoice.com/forums/245727-f-language/suggestions/11125137-expand-support-for-byref-to-match-c-7) at the same time, since it will also affect the safety rules by loosening them in some cases?

**Comment by kbattocchi** [comment]
Regarding my last comment, byref locals and returns have now been merged into the Roslyn tree - see [here](https://github.com/dotnet/roslyn/pull/8030).

**Comment by TIHan** [comment]
This is worth going through.

**Comment by TIHan** [comment]
I've updated the checklist.

These still have issues:

- Compiler allows invalid uses of byref in interface methods #127 (Related to https://github.com/Microsoft/visualfsharp/issues/5459)
- Tupling causes problems in argument poitions #3362

**Comment by TIHan** [comment]
The tupling one is a bit more concerning. We need to always error if we can't guarantee the compiler will not make a tuple, which I don't think we are doing.

**Comment by TIHan** [comment]
We have resolved these in 15.9 now.
