### ISSUE TITLE
[META] Build visualfsharp with dotnet cli

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#958]
build visualfsharp (fsharp.core, fsc, fsi) with  [dotnet cli](https://github.com/dotnet/cli) and [project.json](https://github.com/aspnet/Home/wiki/Project.json-file).

The dotnet cli build doesnt replace fsproj atm, it's used only to compile netcore version of FSharp.Core/fsc package and dogfood F# dotnet cli support (`dotnet-compile-fsc`)
- [x] convert `.fsproj` to `project.json`: (ref #1000)
- [ ] migrate custom msbuild task as dotnet/cli tool
  - [x] FsSrGen: 
    - [x] Use https://github.com/fsprojects/FsSrGen nuget in `master` (ref #962)
    - [x] Use netcore fssrgen tool ( `dotnet-fssrgen` nuget package )
  - [ ] FsLexYacc: 
    1. [ ] Use https://github.com/fsprojects/FsLexYacc nuget in `master` (ref #959)
    2. [ ] Use netcore fslexyacc tools: WIP in fsprojects/FsLexYacc#44 
- [ ] build [test utils in tests/fsharpqa/testenv/src](tests/fsharpqa/testenv/src) with project.json
- [x] build netcore profile
- [ ] create `Microsoft.FSharp.Core.netcore` nuget package
- [ ] create `Microsoft.FSharp.Compiler.netcore` nuget package
#### How to declare defines per target profile

use  `compilationOptions` under `framework` (ref [compilationoptions docs](https://github.com/dotnet/cli/blob/a7f438f85d5a68c8f4c61bb422c39bbf3c1e1822/Documentation/specs/runtime-configuration-file.md#compilationoptions-section-depsjson). 
That's needed to replace conditional defines in msbuild like

``` xml
    <DefineConstants Condition="'$(TargetFramework)'=='coreclr'">$(DefineConstants);PREFERRED_UI_LANG</DefineConstants>
```
#### How to generate and build fs source files

Some .fs source files need to be generated with `FsSrGen` and `FsLexYacc`.

It's possible to use the `precompile` script to run a tool (`dotnet-fssrgen` for example).
But `dotnet build` check if a source file (declared in the `compileFiles`) exists before of running `precompile` script, so stop build before generate the files.

Workaround: create an empty .fs file placeholder.
Long term: dotnet/cli#1475

**Comment by dsyme** [comment]
I'm closing this as it is quite old and the various chances to the .NET CLI mean that the issue description would need to be rewritten
